# General comments to common answers
gen_com_comments = ["WHOOO", "ESKEDIT", "Let\'s gooo",
"You got it!", "Good job!", "All right!", "Fabulous!", "Fantastico!",
"Outstanding!", "Way to go!", "That's grrreat!", "Very nice! I like!",
"No way hosay!", "Tres bien! Hon hon hon baguette.", "Estupendo mon amigos!",
"Eyyyyy", "Attaboy/Attagirl/Atta-Non-binary-individual!",
'MOM GET THE CAMERA!', 'WubalubaDUBDUB!', 'G-G-G-GODLIKE!', 'SAMESIES']

# General comments to skiped answers
gen_skip_comments = ['You\'re tearing me apart, Lisa!', "SAD", ""]

# Questions and general responses to them
common_qs = [
['You are in the last 24 hours of your life, what do you do?', ['']],
["How do you like to 'waste' your time?", ['']],
['If you had your own TV network, what would it be about?', ['Keeping up with the bots00100001']],
['If you had an extra hour every day, what would you do with it?', ['Yeah, I would waste it too.']],
['If you could be any animal, what would you be?', ['']],
['Top shows you binge-watched?', ['Ouuu, I know what I\'m watching tonight!']],
['If you had a time machine, what time period would you go to?', ['Marty, we gotta go back!']],
['If you could only hear a few songs for the rest of your life, what would it be?', ['Friday, friday, gotta get down on Friiiiday', 'Oppa gangnam style!', 'Eyyyyyyyyyyyyy, Macarena!']],
['What is on your bucket list?', ['Sand bucket, ice bucket, mop bucket, any bucket really.']],
['If you could have any superpower, what would you have?', ['']],
['What is your most used emojis?', [':)']],
['What would your dream house be like?', ['Now I\'m wondering what a nightmare house would look like...']],
['You can have an unlimited supply of one thing for the rest of your life, what is it? (Multiple answers allowed)', ['']],
['Who would you swap lives with?', ['No one! I love being a bot... unless?']],
['What was your favorite game when you were a child?', ['Tag you\'re it!', 'Ready or not, here I come!', 'GOAAAAL']],
['What are your favorite midnight snacks?', ['']],
['What are your hidden talents?', ['Stop hiding them!!']],
['What school subjects did you like the least?', ['']],
['What instruments have you played?', ['']],
['If you had to teach a class on anything, what would you teach?', ['']],
['If you could find out one thing about your future using a crystal ball, what would you want to know?', ['']],
['What were some of the happiest moments of your life?', ['That makes me happy :)']],
['What motivates you?', ['']],
['What are your pet peeves?', ['']],
['How would you describe yourself in one word? (feel free to write multiple answers)', ['Indescribable ;)']],
['What are some of your greatest successes?', ['']],
['What do you suck at?', ['Everything.']],
['What do you wish you were really good at?', ['Everything.']],
['How would your friends describe you?', ['']],
['Who do you look up to?', ['I\'m really short, so just about anyone!']],
['Who knows you the best?', ['The noob who coded me...']],
['What is the question people ask you most often?', ['?????']],
['How do you chill with your friends?', ['Chillin like a villain!']],
['What are some school subjects that you loved?', ['']],
['What school clubs would you first join?', ['']],
['What books do you most recommend to people?', ['']],
['Best childhood moments?', ['Awwwww']],
['What jobs have you dreamed of having?', ['']],
['What are your top activities that you like to do?', ['WOW, look at all this space for activities!']],
['When have you felt sad in your life?', ['I\'m not crying, you\'re crying!']],
["What are the craziest adventures you've had?", ['We getting crazy now!']],
['What are your favourite games?', ['IT\'S GAMER TIME']],
['What are your goals in life?', ['Ouuuu, someone\'s ambitious']],
['What websites do you most visit?', ['Surfin the web! Cowabunga dudeeee!']],
['What social media do you use most?', ['But first, let me take a selfie!']],
['If you were stranded on an island, what items would you bring?', ['I just hope we don’t get Lost...']],
['What are your favourite musicians?', ['HEE HEE', 'SKRT SKRT', 'SQUAAAA', 'It\'s lit!',
'ANOTHER ONE', 'D-r-r-r-r-r-r-r-r-AHHHH!', 'SKRAAAAA']],
['What sports do you like to play?', ['SPORTS YEAH']],
['What are some unique things about you?', ['']],
['What foods do you dislike?', ['EWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW']],
['What are some cars you would love to drive?', ['Gotta go FAST!']],
['What would you change about yourself?', ['What are you waiting for??']],
['What are your favourite items of clothing?', ['']],
['If you got a million dollars right now, what would you spend it on?', ['DOLLA DOLLA BILLS Y\'ALL']],
['If you could go anywhere in the world on vacation, where would you go?', ['Let\'s go to Narnia!']],
['What were some of your proudest moments?', ['I\'m proud of you too!']],
['What foods do you love the most?', ['MMMMM Delicious']],
['What pets would you get?', ['Gotta catch them all!']],
['What are your guilty pleasures?', ['Mine is Legally Blonde!']],
['What are you looking forward to most?', ['']],
['What characteristics do you admire (in yourself or others)?', ['']],
['What always makes you laugh?', ['LOL','LMAOOO','LMFAO']],
['What would you do on the perfect day?', ['Do one of those today!']],
['Most important qualities in a friend?', ['All I want is a good coder, is that too much to ask??']],
["What interest haven't you pursued, but have always wanted to?", ['TAKE THE FIRST STEP TODAY!']],
['All-time favourite movies?', ['Life is like a box of chocolates...',
'Who ya gonna call?', 'To infinity and beyond!', 'SAY WHAT AGAIN!', 'Keep the change, ya filthy animal.', 'So you’re telling me there’s a chance.',
'One. Million. Dollars.', 'Stop trying to make fetch happen.', 'That\'s my secret, Captain: I\'m always angry', 'Look at me. I\'m the captain now.']],
['What were some things you geeked-out about?', ['NERDS R US']],
['What do you think the secret to a good life is?', ['Ouuu, I\'m stealing this secret...']],
['If you could go on a road trip with any person (dead or alive), who would you choose?', ['']],
['What were some highlights of the year for you?', ['']],
['If you woke up tomorrow as an animal, what animal would you choose to be?', ['According to my mom, I’m already an animal!']],
['If you could live anywhere on this planet and take everything that you love with you, where would you choose to live?', ['I can show you the world!']],
["What is some items you couldn't live without?", ['I couldn’t live without YOU!']],
['What are some unusual things do you do regularly?', ['Uhh, I’m ganna pretend I didn’t hear that.']],
['What would you like to learn?', ['I love me some learning!']],
['What countries have you visited?', ['']]]
